version: "3.2"
services:
  collectiveaccess:
    build: ./collectiveaccess
    container_name: collectiveaccess
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_DISPLAY_NAME=${APP_DISPLAY_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - TIMEZONE=${TIMEZONE}
    volumes:
      - ./collectiveaccess/media:/var/www/providence/media
    ports:
      - 80:80
    restart: always

